# Page settings

baseURL = "https://dave.levine.org/"
languageCode = "en"
title = "Dave's Resume"
theme = "hugo-devresume-theme"
# googleAnalytics = "UA-XXXXXXX-Y"

[params]
    author = "Dave Levine"
    description = "DevResume - Bootstrap 4 Resume/CV Template For Software Developers"

    primaryColor = "#282a36"
    textPrimaryColor = "#282a36"

    [params.profile]
        enable = true
        name = "Dave Levine"
        tagline = "IT Analyst with 8 years experience and a master’s degree in Information Systems."
        avatar = "avatar.webp"

    [params.contact]
        enable = true
        location = "New York"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:516-455-6778"
        text = "516.455.6778"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:dave@levine.org"
        text = "dave@levine.org"
        [[params.contact.list]]
        icon = "fa fa-file-pdf"
        url = "assets/davelevine-resume.pdf"
        text = "CV / Resume"
        # [[params.contact.list]]
        # icon = "fas fa-globe"
        # url = "#"
        # text = "cv.davelevine.io"

    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "Linux / macOS / Microsoft Windows"
        [[params.skills.list.items]]
        details = "Cloud Services (AWS)"
        [[params.skills.list.items]]
        details = "Virtualization"
        [[params.skills.list.items]]
        details = "Troubleshooting"
        [[params.skills.list.items]]
        details = "ServiceNow"
        [[params.skills.list.items]]
        details = "Visio"
        [[params.skills.list.items]]
        details = "HTML"
        [[params.skills.list.items]]
        details = "Jira"
        [[params.skills.list.items]]
        details = "Excel"
        [[params.skills.list.items]]
        details = "Information Security"
        [[params.skills.list.items]]
        details = "Networking"
        [[params.skills.list.items]]
        details = "Data Loss Prevention"
        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Knowledge Management"
        [[params.skills.list.items]]
        details = "Technical Writing"
        [[params.skills.list.items]]
        details = "Requirements Gathering & Analysis"
        [[params.skills.list.items]]
        details = "Change Management"
        [[params.skills.list.items]]
        details = "Stakeholder Management"
        [[params.skills.list.items]]
        details = "Business Process Improvement"
        [[params.skills.list.items]]
        details = "Software Development Life Cycle (SDLC)"
        [[params.skills.list.items]]
        details = "ITIL"
        [[params.skills.list.items]]
        details = "Agile Development"

    [params.education]
        enable = true

        [[params.education.list]]
        degree = "Certificate in Systems Design"
        university = "Cornell University"
        dates = "2021"
        [[params.education.list]]
        degree = "MS in Information Systems"
        university = "Long Island University"
        dates = "2011 - 2014"
        [[params.education.list]]
        degree = "BS in Information Management & Technology"
        university = "Long Island University"
        dates = "2006 - 2011"

     [params.awards]
         enable = true

         [[params.awards.list]]
         name = "AWS Certified Solutions Architect - Associate"
         body = "Credential ID: 3CX8XLLCN2F11W3T"
         date = "Issued: 2020 | Expires: 2023" 
    #     [[params.awards.list]]
    #     name = "CompTIA Security+"
    #     body = "Credential ID: 8N88HELMPHE4Q6Q2"
    #     date = "Issued: Nov 2016 | Expired: Nov 2019"
    #     [[params.awards.list]]
    #     name = "Microsoft Certified IT Professional [MCITP] (Retired)"
    #     body = "Credential ID: E404-1374"
    #     date = "Issued: Oct 2013 | Expired: Oct 2016"

    # [params.languages]
    #    enable = true

    #    [[params.languages.list]]
    #    name = "English"
    #    level = "Native"
    #    [[params.languages.list]]
    #    name = "Spanish"
    #    level = "Professional"

    # [params.interests]
    #    enable = true

    #    [[params.interests.list]]
    #    name = "Self Improvement"
    #    [[params.interests.list]]
    #    name = "Fatherhood"
    #    [[params.interests.list]]
    #    name = "Weightlifting"
    #    [[params.interests.list]]
    #    name = "Reading"
    #    [[params.interests.list]]
    #    name = "Traveling"

    [params.summary]
        enable = true
        text = "Experienced IT analyst with a proven keen grasp of interpersonal relationship management and technical skills utilized for attaining business goals. Experience includes the successful demonstration of leading cross-functional teams to perform and document insightful assessment of current business processes, technical analyses, quality validation and continuous improvement of web-based solutions."

    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "IT Business Analyst"
        dates = "Dec 2017 - Present"
        company = "Weill Cornell Medicine"
        [[params.experience.list.items]]
        details = "Manage and liaise with stakeholders to gather business requirements, create functional/technical specifications, analyze, and distribute data, and interface with cross-functional teams including Business Intelligence, Application Development, Quality Assurance, Training and Security to ensure business process improvement."
        [[params.experience.list.items]]
        details = "Use key performance metrics and data to provide insights and strategic business recommendations for key stakeholders."
        [[params.experience.list.items]]
        details = "Develop project plans, workflows, training, documentation, and administrative approvals required to advance 5,000+ Weill Cornell research studies."
        [[params.experience.list.items]]
        details = "Design business process workflow diagrams to identify opportunities for business operational improvement."
        [[params.experience.list.items]]
        details = "Maintain business reporting specifications to automate and improve the optimization of Business Intelligence reports."
        [[params.experience.list.items]]
        details = "Conduct quality control testing and gap analysis to create and improve workflows and business processes."

        [[params.experience.list]]
        title = "Application Support Analyst II"
        dates = "Oct 2015 - Dec 2017"
        company = "Weill Cornell Medicine"
        [[params.experience.list.items]]
        details = "Provided Tier 2 end-user support for research application modules."
        [[params.experience.list.items]]
        details = "Provisioned user access rights to research administration application modules."
        [[params.experience.list.items]]
        details = "Collaborated with lead analysts in the implementation,testing & training for new and enhanced functionality."
        [[params.experience.list.items]]
        details = "Created and developed knowledge base in ServiceNow to store documentation, procedures & solutions."

        [[params.experience.list]]
        title = "Systems Support Analyst"
        dates = "Nov 2013 - Oct 2015"
        company = "ClickIT Inc."
        [[params.experience.list.items]]
        details = "Provided Tier 1 end-user support for Microsoft Windows based systems & proprietary surveillance software."
        [[params.experience.list.items]]
        details = "Conducted testing and analysis to enhance video analytics software."
        [[params.experience.list.items]]
        details = "Created and maintained company knowledge base."

    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "Knowledge Base"
        meta = "Open Source"
        tagline = "A knowledge base I started in 2016 to document my homelab. It has since amassed to over 300 articles, guides and documents that serve as a source of truth, second brain and a labor of love."

        [[params.projects.list]]
        title = "Homelab"
        meta = "Open Source"
        tagline = "A personal project focusing on everything from system design and architecture to monitoring and security."

        [[params.projects.list]]
        title = "Self Improvement"
        meta = ""
        tagline = "A never ending journey of personal growth and well-being. Capturing and documenting. Sharing and discussing with others."

    [params.information]
        enable = true

    #    [[params.information.list]]
    #    title = "Papers"
    #    [[params.information.list.items]]
    #    details = "2018 · Lorem Ipsum"
    #    [[params.information.list.items]]
    #    details = "2016 · Sed Fringilla"

        [[params.information.list]]
        title = "Interests"
        details = "Self-Improvement | Fatherhood | Weightlifting | Reading | Traveling"
    #    [[params.information.list.items]]
    #    details = "Fatherhood"
    #    [[params.information.list.items]]
    #    details = "Weightlifting"
    #    [[params.information.list.items]]
    #    details = "Reading"
    #    [[params.information.list.items]]
    #    details = "Traveling"

    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "https://linkedin.com/in/davelevine87"
        title = "davelevine87"
        [[params.social.list]]
        icon = "fab fa-keybase"
        url = "https://keybase.io/davelevine"
        title = "davelevine"
    #    [[params.social.list]]
    #    icon = "fa fa-file-pdf"
    #    url = "https://cv.davelevine.io/assets/davelevine-resume.pdf"
    #    title = "CV / Resume"
        [[params.social.list]]
        icon = "fab fa-github"
        url = "https://github.com/davelevine"
        title = "davelevine"

[params.footer]
    copyright = "Dave Levine"